// @ts-check
import fs from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';

// One sidebar group per feature folder. Starlight would label an autogenerated group with the
// raw folder name, so build the groups here: "payment-plans" -> "Payment plans".
// Reads the synced content, so `npm run sync` must run first (dev and CI both do).
const featuresDir = new URL('./src/content/docs/features/', import.meta.url);
const featureGroups = fs.existsSync(featuresDir)
  ? fs
      .readdirSync(featuresDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => {
        const words = entry.name.replace(/-/g, ' ');
        return {
          label: words.charAt(0).toUpperCase() + words.slice(1),
          collapsed: true,
          items: [{ autogenerate: { directory: `features/${entry.name}` } }],
        };
      })
  : [];

export default defineConfig({
  integrations: [
    // Must come before starlight so it sees ```mermaid blocks first.
    mermaid({ autoTheme: true }),
    starlight({
      title: 'Lizt Docs',
      // Search (Pagefind) is built into Starlight and on by default.
      sidebar: [
        { label: 'Start here', items: ['glossary', 'roles'] },
        { label: 'Features', items: featureGroups },
        {
          label: 'Engineering',
          items: [
            'engineering/architecture',
            { label: 'Decisions', items: [{ autogenerate: { directory: 'engineering/decisions' } }] },
          ],
        },
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
      ],
    }),
  ],
});
